# Generated by Django 6.0.5 on 2026-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.IntegerField()),
                ('oldprice', models.CharField(blank=True, max_length=100, null=True)),
                ('badge', models.CharField(max_length=100)),
                ('badgeColor', models.CharField(choices=[('bg-red-500', 'Red'), ('bg-pink-500', 'Pink'), ('bg-cyan-500', 'Cyan'), ('bg-purple-500', 'Purple')], default='bg-red-500', max_length=100)),
                ('rating', models.FloatField()),
                ('buyers', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
